Repository CustomerAutoZoneSelfService/cazss-frontend, pull requests merged in 2025-05, with the labels that each got.

#12 feat: Execute service conditional rendering if response is a pdf encoded in base 64 (FE-11)
  .gitignore
  e2e/mock/pdfview.test.ts
  src/lib/components/AppContainer.svelte
  src/lib/mockApiWrapper.ts
  src/routes/endpoint/[id]/+page.svelte
Labels: feature

#13 refactor: bring build time fix, Sidebar bugfix, test fix and commit-msg fix to team-4-stable (SCRUM-78)
  .husky/commit-msg
  e2e/initE2EMocked.ts
  src/lib/components/InputTable.svelte
  src/lib/components/Sidebar.svelte
  src/lib/components/UsernameButton.svelte
  src/lucide.d.ts
  tsconfig.json
  vite.config.ts
Labels: bugfix, testing, refactor

#25 chore: base64 to PDF conversion and PDF viewer (FE-13)
  src/lib/components/PdfViewer.svelte
  src/routes/endpoint/[id]/+page.svelte
Labels: feature

#23 feat: implement panel for input/output display (SCRUM-178)
  src/lib/components/EndpointCard.svelte
  src/lib/components/HistoryCardDetailsPanel.svelte
  src/lib/mockApiWrapper.ts
  src/routes/history/admin/+page.svelte
Labels: feature

#21 Feat: pagination on send request (FE-20)
  e2e/initE2EMocked.ts
  e2e/mock/pdfview.test.ts
  src/lib/components/Button.svelte
  src/lib/components/DisplayResultSectionInvokeService.svelte
  src/lib/components/ParameterSectionInvokeService.svelte
  src/lib/components/PdfViewer.svelte
  src/lib/handlers/handleFindRequestKeyValue.ts
  src/lib/handlers/handleInitializeRequestService.ts
  src/routes/endpoint/[id]/+page.svelte
Labels: feature, refactor

#20 refactor: table width and fixed delete button (SCRUM-191)
  src/lib/components/Button.svelte
  src/lib/components/InputTable.svelte
  src/lib/components/TextFormat.svelte
  src/routes/create/+page.svelte
Labels: bugfix, refactor

#33 feat: implement filters page and filtered response (FE-18)
  src/lib/components/CheckBox.svelte
  src/lib/components/DisplayResultSectionInvokeService.svelte
  src/lib/components/FilterSectionInvokeService.svelte
  src/lib/mockApiWrapper.ts
  src/lib/types/RequestService.ts
  src/routes/endpoint/[id]/+page.svelte
Labels: feature
